apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{ if .Values.service.targetPort }} 
    targetPort: {{ .Values.service.targetPort }} 
    {{ else }} 
    targetPort: 3111 
    {{ end }}

  selector:
    app: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}
