namespace:
  name: prod

replicaCount: 5
 
image:
  repository: techtrends
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

service:
  port: 5111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz