namespace:
  name: staging

replicaCount: 3
 
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m

service:
  port: 5111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz