namespace:
  name: sandbox

replicaCount: 1
 
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz